---
title: "Meeting Notes"
format:
  html:
    code-fold: true
jupyter: python3
toc: true
---


# Meeting Notes


## 2022-11-23

We went over the following topics:

- Paper was rejected, even though the most critical reveiwer increased his evaluation.
- It only makes sens to experiment with very simple concepts. 
- We talked about the probing problem discussed in the Chess Knowledge paper. 
    - To evaluate the models mentioned in the paper, we would need to create an experiment.
- We talked about comparing probing methods for two different models. 

TODO:

- [ ] Add more probing models
- [ ] Compare the probing accuracy for the same model at different training steps


## 2022-12-05

Work done:

- Added a neural network probe
- Probed the medium autoencoder during training with three different probing methods
- "The degree of effort" approach reviewed
- Implemented boosting algorithm to approximate degree of effort

Discussion:

- We saw that a linear probe (and the decision tree probe) showed a decrease in probing accuracy in a compressed state while the network was clearly improving. 
- The neural network probe did not show this behavior.
- Thus if we want to use probing to evaluate and compare the quality of a compressed state, we should use a neural network probe.


TODO:

- [ ] Use a neural network probe (linear and decision tree) to evaluate Stockfish NNUE
- [ ] Check if the boosting algorithm sheds light on concept representation.



## 2022-12-07

Work done:

- Imported the officiel NNUE weights 
- Probed the NNUE at two different depths
- Calculated the probing accuracy for number of classification concepts at both depths

Discussion:

- We saw that linear probe was often underperforming at layer1 but not layer2
- No clear pattern was observed for comparison of decision trees and neural network probe

TODO:

- [ ] Implement binary concept: pawn is on Nth rank
- [ ] Perform probing experiment with Regression concepts (stockfish concepts)



## 2022-12-14

Work done:

- Implemented binary concept: pawn is on Nth rank
- Probed pawn rank concept
- Regression experiment failed to converge for second layer
- Regression experiment converged for first layer

Discussion:

- We need to make decisions about publishing 
- Pawn rank concept is very interesting

TODO:

- [ ] Find ways to make the regression experiment converge
- [ ] Try probing experiments per bucket
 

## 2022-12-16

Work done:

- Probed regression concepts by converting them to binary concepts (sign of the concept)
  - Probed per bucket regression concepts


## 2023-02-06


- CoG - https://2023.ieee-cog.org/
- ECAI - https://ecai2023.eu/dates
- Ráðstefnan sem María nefndi - https://www.sciencedirect.com/journal/decision-support-systems/about/call-for-papers#dss-special-issue-on-explainable-ai-for-enhanced-decision-making


TODO:
  - Create a bigger neural probe
  - 